#!/bin/sh
# center current window

. $XDG_CONFIG_HOME/wm.conf

# get current window id, width and height
WID=$(pfw)
WW=$(wattr w $WID)
WH=$(wattr h $WID)

# get screen width and height
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

# move the current window to the center of the screen
wtp $(((SW - WW)/2)) $(((SH - WH + PANELHEIGHT)/2)) $WW $WH $WID
