#!/bin/sh
# put current window into a corner

. $WMCONF

CUR=${2:-$(pfw)}
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

BW=$(wattr b $CUR)
W=$(wattr w $CUR)
H=$(wattr h $CUR)

case $1 in
	tl) X=$GAP Y=$((GAP + PANELHEIGHT)) ;;
	tr) X=$((SW - W - BW*2 - GAP)) Y=$((GAP + PANELHEIGHT)) ;;
	bl) X=$GAP Y=$((SH - H - BW*2 - GAP)) ;;
	br) X=$((SW - W - BW*2 - GAP)) Y=$((SH - H - BW*2 - GAP)) ;;
	*) echo "no position specified" ;;
esac

wtp $X $Y $W $H $CUR
