#!/bin/sh
# focus wrapper that sets borders and can focus next/previous window

. $XDG_CONFIG_HOME/wm.conf

a=0x545466 # active border color
i=0x353540 # inactive border color

# get current window id
c=$(pfw)

setborder() {
	# check if window exists
	wattr $2 || return

	case $1 in
		active)   chwb -s$BORDERWIDTH -c$a $2 ;;
		inactive) chwb -s$BORDERWIDTH -c$i $2 ;;
	esac
}

case $1 in
	next) wid=$(lsw|grep -v $c|sed '1 p;d') ;;
	prev) wid=$(lsw|grep -v $c|sed '$ p;d') ;;
	0x*) wattr $1 && wid=$1 ;;
esac

# exit if another window to focus can't be found
test -z "$wid" && echo "can't find a window to focus" >&2 && exit 1

# set inactive border on current window
setborder inactive $c
# activate the new window
setborder active $wid
# put it on top of the stack
chwso -r $wid
# set focus on it
wtf $wid
