#!/bin/sh
# focus wrapper that sets borders and can focus next/previous window
# copyright 2016 (c) z3bra & kori

. $XDG_CONFIG_HOME/wm.conf

# get current window
# falls back to root window ID, this is a hack.
cur=$(pfw || echo "0x00000000")

setBorder() {
	a=0x545466 # active border color
	i=0x353540 # inactive border color

	case $1 in
		active)   chwb -s$BORDERWIDTH -c$a $2 ;;
		inactive) chwb -s$BORDERWIDTH -c$i $2 ;;
	esac
}

case $1 in
	next) new=$(lsw | grep -v "${cur}" | sed '1 p;d') ;;
	prev) new=$(lsw | grep -v "${cur}" | sed '$ p;d') ;;
	0x*) wattr $1 && new=$1 ;;
esac

# exit if another window to focus can't be found
[ -z "${new}" ] && echo "can't find a window to focus" && exit 1

# set inactive border on current window
setBorder inactive ${cur}
# activate the new window
setBorder active ${new}
# put it on top of the stack
chwso -r ${new}
# set focus on it
wtf ${new}
