#!/bin/sh
# light (window) advent daemon
# ^ backronym, I just wanted to make the "exec wew | lad" pun on my xinitrc

while IFS=: read ev wid; do
	case $ev in
		# Focus new windows
		16) wattr o $wid || focusw $wid ;;

		# Mapping requests
		19) wattr o $wid || focusw $wid ;;

		# Focus next window when deleting current window
		18) wattr m $wid || focusw prev ;;

		# Focus entered window
		7) wattr o $wid || focusw $wid ;;

		# google play music notification
		146) focusw prev ;;
	esac
done
