#!/bin/sh
# le (window) advent daemon

while IFS=: read ev wid; do
    case $ev in
        # window creation
        16) wattr o $wid || focusw $wid ;;

        # mapping requests
        19) wattr o $wid || focusw $wid ;;

        # focus next window when deleting focused window
        18) wattr $(pfw) || focusw prev 2>/dev/null;;

        # entering window
        7) wattr o $wid || focusw $wid ;;
    esac
done
