#!/bin/sh
# move window to a predefined location
# copyright 2016 (c) z3bra & kori

. $XDG_CONFIG_HOME/wm.conf

cur=$(pfw)          # current window
root=$(lsw -r)      # root window ID

sw=$(wattr w $root) # screen width
sh=$(wattr h $root) # screen height
w=$(wattr w $cur)   # window width
h=$(wattr h $cur)   # window height

case $1 in
	topLeft)
		x=$GAP
		y=$((GAP + PANELHEIGHT)) ;;

	topRight)
		x=$((sw-w - BORDERWIDTH*2 - GAP))
		y=$((GAP + PANELHEIGHT)) ;;

	bottomLeft)
		x=$GAP
		y=$((sh-h - BORDERWIDTH*2 - GAP)) ;;

	bottomRight)
		x=$((sw-w - BORDERWIDTH*2 - GAP))
		y=$((sh-h - BORDERWIDTH*2 - GAP)) ;;

	centerScreen)
		x=$(((sw - w)/2))
		y=$(((sh-h + PANELHEIGHT)/2)) ;;

	*) echo "no position specified" ;;
esac

wtp $x $y $w $h $cur
