#!/bin/sh
# move window to a predefined location
# copyright 2016 (c) z3bra & kori

. $XDG_CONFIG_HOME/wm.conf

cur=${2:-$(pfw)}
root=$(lsw -r)
sw=$(wattr w $root)
sh=$(wattr h $root)

bw=$(wattr b $cur)
w=$(wattr w $cur)
h=$(wattr h $cur)

case $1 in
	topLeft)      X=$GAP Y=$((GAP + PANELHEIGHT)) ;;
	topRight)     X=$((sw - w - bw*2 - GAP)) Y=$((GAP + PANELHEIGHT)) ;;
	bottomLeft)   X=$GAP Y=$((sh - h - bw*2 - GAP)) ;;
	bottomRight)  X=$((sw - w - bw*2 - GAP)) Y=$((sh - h - bw*2 - GAP)) ;;
	centerScreen) X=$(((sw - w)/2)) Y=$(((sh - h + PANELHEIGHT)/2)) ;;
	*) echo "no position specified" ;;
esac

wtp $X $Y $w $h $cur
