#!/bin/sh
# zoom a window
# copyright 2016 (c) z3bra & kori

. $XDG_CONFIG_HOME/wm.conf

h=$(wattr h $(lsw -r))
w=$(wattr w $(lsw -r))

# this file is used to store the previous geometry of a window
FSDIR=$TMPDIR/wm/zoom.d
FSFILE=$FSDIR/$(pfw)

# if this file exists, that window is zoomed, so unzoom it and delete file
if test -f $FSFILE; then
	wtp $(cat $FSFILE) $1
	rm -f $FSFILE
else
	# save geometry
	wattr xywh $1 > $FSFILE
	# zoom the window
	wtp $GAP $((PANELHEIGHT + GAP))    \
	    $((w - 2*GAP - 2*BORDERWIDTH)) \
	    $((h - 2*GAP - PANELHEIGHT - 2*BORDERWIDTH)) $1
fi

# focus the window
focusw $1
